### ISSUE TITLE
このリポジトリのコードはMVでも動作すべきか

### ISSUE THREAD

**Issue by elleonard** [Sigureya/RPGmakerMZ#2]
表題の通り、このリポジトリにあるプラグインはMVでも動くことを想定した書かれ方をしているように見受けられますが、方針としてあえてそうされているのでしょうか。
@target 設定はMZになっているが、これはMZに対応しているという意味であって、MV対応を打ち切っていることを意味するものではない、という理解で間違いないでしょうか。

MVでの動作については互換性を保ったままメンテナンスしていく方針かどうか、またその方針をとるに至った理由が知りたいです。

念の為の補足ですが、MV互換性を捨てるべきであると言っているわけではありません。
このリポジトリの方針として互換性を保ったまま保守していく、ということであれば、PRを出させていただく際にはそれに従いたいと考えているため、しぐれんさんのお考えを知りたい次第です。

**Comment by Sigureya** [comment]
MV互換性ですが、以下の理由で維持しています。

MV専用のプラグインのメンテナンスが手間
MZと共用にして、メンテナンスコストを低減しています。
MV用のプラグインの修正の際は、MZ対応改造を行っています。
なお、修正の際はMZ向けに調整した上で、MVではMZのコードを追加して対応しています。

target MZはMZで警告されないようにするための表記としてのみ考えています
MVを追加しても機能上は問題ないので、今後は追加していきます。

**Comment by elleonard** [comment]
ご回答ありがとうございます。MVMZ共用プラグインを管理していく旨、承知しました。
